# Generated by Django 4.2.9 on 2024-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='in_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
